FROM python:3.11-slim

WORKDIR /app

# Install dependencies
COPY crawlers/youtube/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --no-cache-dir flask requests

# Application code
COPY crawlers/youtube/*.py .
COPY crawlers/common/ ./common/

CMD ["python", "run_crawler.py"]
